### ISSUE TITLE
Original error: IO Exception (2): No such file or directory

### ISSUE THREAD

**Issue by haizadtarik** [RoverRobotics/openrover-ros2#8]
I tried to run this packages on the NUC from the SLAM Packages but encountered the following error:
`[bno055_driver-2] [ERROR] []: Caught exception in callback for transition 10`
`[bno055_driver-2] [ERROR] []: Original error: IO Exception (2): No such file or directory, file /home/snuc/ros2_ws/src/serial/src/impl/unix.cc, line 151.`
`[bno055_driver-2] [WARN] []: Error occurred while doing error handling.`

I've checked the serial folder and the file unix.cc existed

**Comment by rotu** [comment]
That error is misleading.

The file `unix.cc` is not missing - the device it's trying to open is. https://github.com/RoverRobotics-forks/serial-ros2/blob/51741829c024d14a90950d9d77422338a09ddd9e/src/impl/unix.cc#L139-L152

Make sure the bno055 driver is connected and confirm what device it's showing up as on your system.
